name: mssql-dev-container

services:
    app:
        image: mcr.microsoft.com/devcontainers/dotnet

        depends_on:
            - db

        volumes:
            - ../..:/workspaces:cached

        # Overrides default command so things don't shut down after the process ends.
        # command: sleep infinity

        # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
        network_mode: service:db

        # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
        # user: root

        # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
        # (Adding the "ports" property to this file will not forward from a Codespace.)

        # Can also use following settings to keep the container running
        stdin_open: true

    db:
        image: mcr.microsoft.com/mssql/server
        restart: unless-stopped

        ports:
            - 1433:1433

        # build:
        #   context: ../
        #   dockerfile: Dockerfile

        environment:
            # https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: P@ssw0rd
            MSSQL_PID: Developer

        volumes:
            - ..:/var/opt/mssql/workspaces

        # Add "forwardPorts": ["db:1433"] to **devcontainer.json** to forward MSSQL locally.
        # (Adding the "ports" property to this file will not forward from a Codespace.)
